# Generated by Django 6.0.4 on 2026-05-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='item_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(choices=[('PAINT', 'Painting'), ('SCULP', 'Sculpture'), ('DIGIT', 'Digital Art'), ('SKETC', 'Sketch')], default='PAINT', max_length=100),
        ),
        migrations.AlterField(
            model_name='art',
            name='item_description',
            field=models.TextField(max_length=120),
        ),
    ]
